apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: monolith-otel-app
  labels:
    app.kubernetes.io/name: app
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app.kubernetes.io/name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: monolith-otel-app
  labels:
    app.kubernetes.io/name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          env:
            - name: PGPASSWORD
              value: orders
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres.monolith-otel-data.svc.cluster.local -U orders -d orders; do
                echo "waiting for postgres"
                sleep 2
              done
      containers:
        - name: app
          image: monolith-otel-lab:k8s-local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres.monolith-otel-data.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: orders
            - name: DB_USERNAME
              value: orders
            - name: DB_PASSWORD
              value: orders
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monolith-otel-observability.svc.cluster.local:4318/v1/traces
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
